name: Gerar APK Android

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o codigo
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gerar chave debug.keystore fixa
        run: |
          keytool -genkeypair -v \
            -keystore debug.keystore \
            -storepass android \
            -keypass android \
            -alias androiddebugkey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -startdate "2026/01/01 00:00:00" \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Instalar e configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'

      - name: Compilar o APK
        run: gradle assembleDebug -Djava.awt.headless=true

      - name: Renomear APK com a versao
        run: |
          TAG_NAME="v1.0.${{ github.run_number }}"
          REPO_NAME="${{ github.event.repository.name }}"
          # Encontra o arquivo gerado pelo build e renomeia
          ORIGINAL_APK=$(ls app/build/outputs/apk/debug/*.apk | head -n 1)
          cp "$ORIGINAL_APK" "app/build/outputs/apk/debug/${REPO_NAME}-${TAG_NAME}.apk"

      - name: Salvar APK nos Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-apk
          path: app/build/outputs/apk/debug/*-v*.apk

      - name: Publicar direto no Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v1.0.${{ github.run_number }}"
          name: "Versão 1.0.${{ github.run_number }}"
          body: "Instalador do ${{ github.event.repository.name }} versão 1.0.${{ github.run_number }} gerado automaticamente!"
          files: app/build/outputs/apk/debug/*-v*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
